spring:
  application:
    name: bravo-inventory-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/bravo_inventory}
    username: ${DB_USERNAME:bravo}
    password: ${DB_PASSWORD:bravo}
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        escapeSyntaxCallMode: callIfNoReturn

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: DEBUG
    com.bravo: TRACE
